export type SkillPreset = {
  id: string;
  name: string;
  iconUrl: string;
  variableCast: number;
  fixedCast: number;
  postCast: number;
  cooldown: number;
};

export const skillPresets: SkillPreset[] = [
  {
    id: "focused-arrow-strike",
    name: "Focused Arrow Strike",
    iconUrl: "/skill-icons/focused-arrow-strike.png",
    variableCast: 0.5,
    fixedCast: 0.5,
    postCast: 0.5,
    cooldown: 0.15,
  },
  {
    id: "aimed-bolt",
    name: "Aimed Bolt",
    iconUrl: "/skill-icons/aimed-bolt.png",
    variableCast: 2,
    fixedCast: 1,
    postCast: 2,
    cooldown: 1,
  },
  {
    id: "crescive-bolt",
    name: "Crescive Bolt",
    iconUrl: "/skill-icons/crescive-bolt.png",
    variableCast: 1,
    fixedCast: 1,
    postCast: 0.5,
    cooldown: 0.15,
  },
  {
    id: "wind-cutter",
    name: "Wind Cutter",
    iconUrl: "/skill-icons/wind-cutter.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 0.3,
  },
  {
    id: "sonic-wave",
    name: "Sonic Wave",
    iconUrl: "/skill-icons/sonic-wave.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 1.75,
  },
  {
    id: "ignition-break",
    name: "Ignition Break",
    iconUrl: "/skill-icons/ignition-break.png",
    variableCast: 1,
    fixedCast: 0,
    postCast: 0,
    cooldown: 2,
  },
  {
    id: "overbrand",
    name: "Overbrand",
    iconUrl: "/skill-icons/overbrand.png",
    variableCast: 0,
    fixedCast: 0.5,
    postCast: 1,
    cooldown: 0.3,
  },
  {
    id: "rolling-cutter",
    name: "Rolling Cutter",
    iconUrl: "/skill-icons/rolling-cutter.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.2,
    cooldown: 0,
  },
  {
    id: "cross-impact",
    name: "Cross Impact",
    iconUrl: "/skill-icons/cross-impact.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 0.35,
  },
  {
    id: "fatal-menace",
    name: "Fatal Menace",
    iconUrl: "/skill-icons/fatal-menace.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 0,
  },
  {
    id: "triple-shot",
    name: "Triple Shot",
    iconUrl: "/skill-icons/triple-shot.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.35,
    cooldown: 0.2,
  },
  {
    id: "cart-cannon",
    name: "Cart Cannon",
    iconUrl: "/skill-icons/cart-cannon.png",
    variableCast: 3,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 0,
  },
  {
    id: "adoramus",
    name: "Adoramus",
    iconUrl: "/skill-icons/adoramus.png",
    variableCast: 2,
    fixedCast: 0.5,
    postCast: 0.5,
    cooldown: 2.5,
  },
  {
    id: "flamen",
    name: "Flamen",
    iconUrl: "/skill-icons/flamen.png",
    variableCast: 5,
    fixedCast: 1.5,
    postCast: 1,
    cooldown: 3,
  },
  {
    id: "arbitrium",
    name: "Arbitrium",
    iconUrl: "/skill-icons/arbitrium.png",
    variableCast: 4,
    fixedCast: 1.5,
    postCast: 0.5,
    cooldown: 3,
  },
  {
    id: "picky-peck",
    name: "Picky Peck",
    iconUrl: "/skill-icons/picky-peck.png",
    variableCast: 1,
    fixedCast: 0,
    postCast: 1,
    cooldown: 0,
  },
  {
    id: "soul-expansion",
    name: "Soul Expansion",
    iconUrl: "/skill-icons/soul-expansion.png",
    variableCast: 2,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 0,
  },
  {
    id: "axe-tornado",
    name: "Axe Tornado",
    iconUrl: "/skill-icons/axe-tornado.png",
    variableCast: 0,
    fixedCast: 0,
    postCast: 0.5,
    cooldown: 2,
  },
  {
    id: "vulcan-arm",
    name: "Vulcan Arm",
    iconUrl: "/skill-icons/vulcan-arm.png",
    variableCast: 0.2,
    fixedCast: 0,
    postCast: 0.1,
    cooldown: 0.1,
  },
  {
    id: "arm-cannon",
    name: "Arm Cannon",
    iconUrl: "/skill-icons/arm-cannon.png",
    variableCast: 2,
    fixedCast: 0.1,
    postCast: 0.5,
    cooldown: 0.15,
  },
];
